GoogleChrome/dialog-polyfill

tests/fancy-modal-dialog.html

remove some classList use, clean up optional css

---

dialog-polyfill.js
suite.js

only vertically center modal dialogs

---

README.md
dialog-polyfill.js
suite.js

use DOMNodeRemoved to watch for modal dialog removal from DOM

---

dialog-polyfill.js

don't bubble the close event, conform to spec

---

dialog-polyfill.js
suite.js

Resolves #21.
@jeffutter @ThiRaBrTNK

Break apart registerDialog and forceRegisterDialog

---

dialog-polyfill.js
suite.js

update form method='dialog' to support button value, fix default returnValue

---

dialog-polyfill.js

This probably works, but I don't currently have an IE9/10 machine to test on.

domattr support for IE9 and IE10

---

dialog-polyfill.js
suite.js

@elektronik2k5
Fixes #77. Thanks for the pointer!

allow form inside dialog without specified method

---

README.md

Attempting to help clear up usage for starters. Took me a while to realize I needed to call registration since it isn't clearly pointed out in the code sample.

Add usage section to readme.

---

dialog-polyfill.js

See [description](https://www.tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/)  problem

Bugfix for IE when blur occurs on <body>

---

dialog-polyfill.js

string errors -> Error

---

dialog-polyfill.js
suite.js

@ThiRaBrTNK @Garbee 
Resolves #33 and updates tests.

focus on show() as well as showModal()

---

suite.js

test for dialog positioning

---

dialog-polyfill.js
suite.js
tests/form.html
tests/modal-dialog.html

focus work preventing stuck

---

dialog-polyfill.js
suite.js

downgrade dialog elements removed/added immediately

---

dialog-polyfill.js
suite.js

Resolves #141.
PTAL @steffenweber

look for form submitter with click

---

dialog-polyfill.js
suite.js

Resolves #144.
I'm not sure anyone has ever actually wanted this feature, but hey!

support type="image" for submits

---

dist/dialog-polyfill.esm.js
dist/dialog-polyfill.js
index.js
suite.js

Adhere to `event.defaultPrevented` on form submit events

---

dist/dialog-polyfill.esm.js
dist/dialog-polyfill.js
index.js
package-lock.json

Added and used the `isConnected` function in order to reliably check whether an element is attached to DOM.

Fix showModal error inside shadow DOM (#186)

---

index.d.ts

Fixes GoogleChrome/dialog-polyfill#204
Should not have an impact on the cjs types.

Fix types for ESM

---

dist/dialog-polyfill.esm.js
dist/dialog-polyfill.js
index.js
package-lock.json
package.json

Fix for issue #189 - allow DOM traversal in shadow DOM contexts.

Fix detection of nearest dialog for shadow DOM usage (#189)

---

dist/dialog-polyfill.esm.js
dist/dialog-polyfill.js
index.js
package.json

fix possible .submitter being null
