GoogleChrome/dialog-polyfill

README.md, dialog-polyfill.js
Remove some code that supported IE8. Notably-
* JavaScript- we use `Function.prototype.bind`, `Array.prototype.indexOf`, `addEventListener`, `removeEventListener` and `getComputedStyle`
* CSS- we use `rgba()` for colors (not supported in IE8, but already used in a few places within this polyfill)
Also updates the `README.md` to indicate that we support modern browsers along with IE9 and above.
=> Minimum version to IE9

dialog-polyfill.js
The problem on line 4 has to do with the IE 10 implementation of new CustomEvent( ).
The value needs to be one of the predefined values or it will throw a "Object doesn't support this action" error 
document.createEvent("CustomEvent"); - this will work
and then you use
CustomEvent::initCustomEvent() - to define the type as something other than "CustomEvent"
Or for IE 10 just fallback to the IE9 workaround as shown in the PR.
=> Add IE 10+ compatibility to supportsCustomEvent

package.json
I, as well as many others, use npm for front-end package management.  For example, using with webpack.  This would add support for npm.
I would recommend you add this to the npm registry, but that's not strictly necessary.
=> Added package.json for npm usage

README.md
Browsers without native support for the backdrop pseudo-element will ignore the entire ruleset as they do not understand the selector.
I realise this is possibly pedantry, so feel free to discard.
=> Split polyfill and native backdrop css examples

README.md, dialog-polyfill.js, suite.js
This is a pretty big refactor. It basically more neatly creates a parallel `dialogPolyfillInfo` class alongside each upgraded `dialog`.
Some benefits-
- the `open` property is now just a proxy for the `open` attribute, and some associated benefits
- clearer modal dialog removal, and future-proofing for observers
@wibblymat
=> adds dialogPolyfillInfo, a class that encapsulates the dialog behaviour

dialog-polyfill.js
When documents are served with the "application/xhtml+xml" Content-Type header, then the nodeName is not automatically converted to upper case.
https://wiki.whatwg.org/wiki/HTML_vs._XHTML
=> Support case insensitive nodeName matching

dialog-polyfill.js
The spec dictates that if the dialog is displayed in centered-alignment and the dialog is taller than the viewport, then the dialog shall be placed at the top of the viewport.  Instead, the polyfill was always centering the dialog even if it was taller than the viewport.
https://html.spec.whatwg.org/multipage/forms.html#centered-alignment
=> Fixed centered-alignment if dialog is taller than the viewport.

dialog-polyfill.js
This second last line of the showModal function failed in my application as the activeElement doesn't seem to have a blur function. The last line of the function would have set the focus. This line wasn't executed anymore.
=> The activeElement doesn't seem to have blur in IE 11.0.9600.18015

dialog-polyfill.js
Closes #93.
Also, I’ve removed `forceRegisterDialog` and `registerDialog` methods since they’re already defined on `dialogPolyfill` object which is exported to `window`. I suppose that’s OK?
=> Don’t expose polyfill to global when in CJS/AMD

dialog-polyfill.js, suite.js
This is a quick fix for now, but with a couple of caveats-
* `aria-hidden` is not set (see [spec](https://www.w3.org/TR/wai-aria/complete#aria-hidden)), and it's not clear that a dialog being implicitly hidden via CSS is helpful
* arguably, a modal dialog should be an [alertdialog](https://www.w3.org/TR/wai-aria/complete#alertdialog) (but, dialogs can be shown in either way, so this would change)
=> add role dialog to upgraded dialogs

dialog-polyfill.js
In environments like electron, `module['exports']` could also be available, when the website code is using AMD. Previous module definition code was preventing dialog polyfill from being defined as an AMD module in electron since it was cheking CJS module availability first, this PR prioritises AMD definition.
=> Prioritise AMD module definition

dialog-polyfill.js
Polyfills probably don't need to warn users that their browser already supports the feature they're polyfilling.
i.e. https://youtu.be/VTp5MTlq4GU?t=70
=> Remove warning that browser already supports <dialog>

README.md
Removed from spec: https://github.com/whatwg/html/pull/2158
No need to keep this in the readme since it won't ever be supported nor is spec-wise needed anymore.
=> Remove anchoring reference.

dialog-polyfill.js, suite.js
Fixes #103 and #72.
This may actually fix other issues; `DOMNodeRemoved` wasn't firing as expected. Now the event is set on the element itself, and it's only relevant where we don't have `MutationObserver` anyway.
=> flip to MutationObserver for more things

README.md, dialog-polyfill.js, suite.js, tests/stacking.html
This fixes a certain class of stacking context problems (so that the dialog still does something...) and warns heavily.
=> stacking context fixes

README.md
This means that the script won't block rendering earlier than needed. A preferable solution would be to use the `async` HTML attribute, but that would require a way to put the custom code in a callback, and this library isn't ready for that yet.
If you don't want to change the example code, than at least document that the script tag's location is not required to be in the <head> section. As it stands, developers that are using the polyfill do not know the best place to put it by default as you said, because it doesn't just depend on the site infrastructure, it also depends on the behaviour of the script. For example, if a script is calling document.write, it will behave differently depending on whether it's in the <head> section or not. Even if I fully review the script's code and …
=> Move the script tag to the body in the example

dialog-polyfill.js, suite.js
When pressing the tab key in firefox caused an undefined reference error to be hit. Looks like maybe it was a regression introduced by commit 76112e8c75fee6b8312dff78105e31d0ba1c112b
I wasn't sure how to write a test to validate that the behavior is actually correct, so I just wrote one that caused the error.
=> fixed undefined variable usage

dialog-polyfill.js, suite.js
=> replaces HTMLFormElement.prototype.submit as it doesn't call submit

dialog-polyfill.js
The `DOMNodeRemoved` event bubbles, which incorrectly causes `downgradeModal()` in IE9/10 when the content changes.
=> Fix DOMNodeRemoved bubble (Issue #150)

dialog-polyfill.js
Avoid using a block scoped function. Closure-compiler now errors in this case if the language_out flag is less than ECMASCRIPT6.
FYI I'm not sure how to run the tests.
=> Refactor from a function to a function expression to avoid block scoping

dist/dialog-polyfill.js
Some existing browser implementations of `HTMLDialogelement` already handle the `onclose` property. Since `onclose` defines a single handler, it is extremely useful when reusing dialogs, as opposed to `addEventListener()`, where there is no ready or easy or clean way to clear any existing handlers. With `onclose`, a dialog element can be used as a template and just have `onclose` assigned to whatever handler if and when necessary.
=> Support for explicit `onclose` handler

index.js
When searching for a focusable item, we need to consider that the dialog may contain custom elements which have shadow roots. If we fail to find a focusable target by conventional means, look for custom elements (must have a '-' in the tag name) and search their shadow roots recursively.
=> Support finding focusable items in custom element shadow roots

index.js
In my application, I detect clicks on the backdrop by comparing the `MouseEvent`'s x and y coordinates to the dialog's box dimensions and closing the dialog if the user clicked on the backdrop.
However I can't simply use the 'click' event because my dialogs are resizable (using the browser native resize grip in the bottom-right corner of the dialog). If a user drags the resize handle to make the dialog bigger - and if the dialog has a `max-width` and/or `max-height` and the user keeps on dragging the mouse cursor and releases their mouse button over the backdrop then the 'click' event is raised with the `MouseEvent` coordinates over the backdrop - so I use the mouseup and mousedown events to detect if the mouse moved between the backdrop and the dialog-proper (again, by comparing …
=> Forward mouseup and mousedown too.

README.md
While the files are the same now, better to point to `dist` ESM instead of source in case source files are split up or require dependencies.
=> Use long-term stable URL
